//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database0Entities : DbContext
    {
        public database0Entities()
            : base("name=database0Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<HDD> HDD { get; set; }
        public virtual DbSet<MB> MB { get; set; }
        public virtual DbSet<PS> PS { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table> Table { get; set; }

        private static database0Entities context;
        public static database0Entities GetContext()
        {
            if (context == null)
            {
                context = new database0Entities();
            }
            return context;
        }
    }
}
